### ISSUE TITLE
match_template SumOfSquaredErrorsNormalized: thread 'main' panicked at 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by bbigras** [PistonDevelopers/imageproc#293]
It seems fine with `MatchTemplateMethod::SumOfSquaredErrors` but not with `MatchTemplateMethod::SumOfSquaredErrorsNormalized`.

imageproc d19cae6dea42a96204e412b179576577c20a6e5b
image 0.20.1

```rust
use failure::Error;
use image::{GrayImage, Luma};
use imageproc::definitions::Image;
use imageproc::map::map_colors;
use imageproc::template_matching::{find_extremes, match_template, MatchTemplateMethod};

use std::f32;

fn convert_to_gray_image(image: &Image<Luma<f32>>) -> GrayImage {
    let mut lo = f32::INFINITY;
    let mut hi = f32::NEG_INFINITY;

    for p in image.iter() {
        lo = if *p < lo { *p } else { lo };
        hi = if *p > hi { *p } else { hi };
    }

    let range = hi - lo;
    let scale = |x| (255.0 * (x - lo) / range) as u8;
    map_colors(image, |p| Luma([scale(p[0])]))
}

fn main() -> Result<(), Error> {
    let image1 = image::open("image.png")?.to_luma();
    let template1 = image::open("template.png")?.to_luma();

    let img = match_template(
        &image1,
        &template1,
        MatchTemplateMethod::SumOfSquaredErrorsNormalized,
    );

    let img = convert_to_gray_image(&img);

    let result = find_extremes(&img);

    println!("result: {:#?}", result);

    Ok(())
}
```

backtrace
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/bbigras2/.cargo/git/checkouts/imageproc-bd69ea4adb8f029e/d19cae6/src/integral_image.rs:151:15
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: imageproc::integral_image::sum_image_pixels
             at /home/bbigras2/.cargo/git/checkouts/imageproc-bd69ea4adb8f029e/d19cae6/src/integral_image.rs:151
  10: imageproc::template_matching::normalization_term
             at /home/bbigras2/.cargo/git/checkouts/imageproc-bd69ea4adb8f029e/d19cae6/src/template_matching.rs:78
  11: imageproc::template_matching::match_template
             at /home/bbigras2/.cargo/git/checkouts/imageproc-bd69ea4adb8f029e/d19cae6/src/template_matching.rs:57
  12: test_imageproc::main
             at src/main.rs:27
  13: std::rt::lang_start::{{closure}}
             at /rustc/de9666f123e800d5fc34210f23127aa6a5d6e4ef/src/libstd/rt.rs:74
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  17: std::rt::lang_start
             at /rustc/de9666f123e800d5fc34210f23127aa6a5d6e4ef/src/libstd/rt.rs:74
  18: main
  19: __libc_start_main
  20: _start
             at ../sysdeps/x86_64/start.S:120
```

image.png
![image](https://user-images.githubusercontent.com/24027/50096105-efde3800-01e4-11e9-907d-6132a4c6e568.png)

template.png
![image](https://user-images.githubusercontent.com/24027/50096138-01274480-01e5-11e9-8283-f938fdf2ed46.png)

**Comment by theotherphil** [comment]
Thanks for the bug report. I'll have a look later this week.

**Comment by theotherphil** [comment]
The normalisation term is computed using an integral image containing the squares of the values of the input image pixels. This was originally intended to be used for very small images, so the sum of the squares of pixels in the image are stored at type u32, and the intermediate calculations are computed at type i32.

To fix this we need implementations of the integral_image functions that use a larger integer type and to use those from the template matching code.

**Comment by theotherphil** [comment]
@bbigras please try again after the latest commit to confirm that this now works correctly.
